### ISSUE TITLE
NameError (uninitialized constant Conekta::ValidationError)

### ISSUE THREAD

**Issue by ingluisdmz** [conekta/conekta-ruby#16] opened 2015-04-27 21:00 UTC
Hello i have a this error:
 def action
   	require "conekta"
	Conekta.locale = :es
	Conekta.api_key = "ENV['PRIVATE_KEY_KONECTA']"
				
	pago=OnlinePayment.create!(:empresa_id => current_empresa.id,:cantidad => params[:card][:cantidad],:active => true,:token_card => params[:token_pago],:pagado => false,:nombre => params[:card][:name])
	
pago.token_card="tok_test_visa_4242"
				
				charge = Conekta::Charge.create({
				    amount: pago.cantidad,
				    currency: "MXN",
				    description: "Recompensa",
				    reference_id: pago.id,
				    card: pago.token_card, 
				    details: {
				      email: "luisdmz92@gmail.com"
				    }
				})

				puts charge.to_s

		rescue Conekta::ValidationError => e
		  puts e.message_to_purchaser 
		#some of the parameters were invalid
		rescue Conekta::ProcessingError => e
		  puts e.message_to_purchaser 
		#the card could not be processed
		rescue Conekta::Error
		  puts e.message_to_purchaser 

		rescue Exception => e
			puts e
			render :json => {:success => 0,:message => e.message}, :callback => params[:callback]
		end
end

**Comment by MauricioMurga** [comment] 2015-04-28 00:29
Hi @ingluisdmz, this is not a bug, it should be Conekta:: ParameterValidationError. There is a mistake in the documentation and we will be fixed shortly.

**Closed by MauricioMurga** 2015-04-28 00:29 UTC

**Comment by obelich** [comment] 2015-07-07 05:24
ok ok if you know what is the error and the documentation is wrong can please tell to us what is the error i use this 

```
  def charge
    begin
      @charge = Conekta::Charge.create({
        amount: params['chargeInCents'],
        currency: "MXN",
        description: "Pizza Delivery at test",
        reference_id: "001-id-test",
        details:
        {
          email: params['emailBuyer']
        },
        card: params['conektaTokenId']
      })
    rescue Conekta::ParameterValidationError => e
      puts e.message_to_purchaser #alguno de los parámetros fueron inválidos
    rescue Conekta::ProcessingError => e
      puts e.message_to_purchaser #la tarjeta no pudo ser procesada
    rescue Conekta::Error
      puts e.message_to_purchaser 
      #un error ocurrió que no sucede en el flujo normal de cobros como por ejemplo un auth_key incorrecto
    end
  end
```

and i get 
undefined method `message_to_purchaser' for nil:NilClass

and i use the code from the example hello ruby :( i make new proyect and move it to the new one

**Comment by MauricioMurga** [comment] 2015-07-07 22:43
Hi @obelich. Sorry for the late response. You are right, the example has a bug and has been updated in this [commit](https://github.com/conekta/conekta-ruby/commit/6084fb4b917bd68b203cb92aa712a05d52e34e47)

As for the official [conekta-docs](https://www.conekta.io/es/docs). We will update them shortly.

If you have further questions, do not hesitate to contact us.

**Comment by obelich** [comment] 2015-07-07 22:45
ok thanks
